### PR TITLE
Add OrderTypes and ServiceTypes to constants

### PR DESCRIPTION
**Pull request by joshiefishbein**
Receiving three (seemingly irrelevant) failures when running Karma:

screen shot 2019-02-01 at 2 34 19 pm
screen shot 2019-02-01 at 2 34 13 pm
screen shot 2019-02-01 at 2 34 05 pm

Should I:
- fix these here?
- fix these in another PR?
- ignore these errors for now?

### CODE REVIEW

**Comment by hhff** [comment]
u r getting these errors because the wrong Brandibble.js instance is being loaded

**Comment by joshiefishbein** [comment]
Related to: https://github.com/BetterBOH/open-tender-skeleton/pull/104

**Comment by hhff** [comment]
@ellismarte can help

**Comment by joshiefishbein** [comment]
Ok @hhff I updated the local brandibble.js I was running against and this works now without errors

**Comment by joshiefishbein** [comment]
Moving this to be exported from `brandibble.js`

**Pull request closed without merging**
